name: Build & Run all tests (release)

on:
    push:
    pull_request:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    
    build-Net40:
        name: .Net Framework 4.0 test
        runs-on: windows-2019
        steps:
          - uses: actions/checkout@v4
          
          - name: run docker
            run: |
            
                # Start-Process -FilePath '0.exe' -Wait -NoNewWindow
                
                docker build -f Net40.dockerfile -t net40 .
                docker run -d --name net40-cont net40
                docker cp 0.exe net40-cont:/app/
                docker exec net40-cont /app/0.exe
          
          - name: temp
            run: |
            
                dotnet --list-runtimes
                dotnet --list-sdks
          
          - name: check pack changes
            run: |
            
                git config --global core.autocrlf false
                git config --global user.name "sun pack bot"
                git config --global user.email "sunserega2@gmail.com"
                git config --global --add url.https://github.com/.insteadOf "git@github.com:"
                
                git push origin --delete "win-pack-changes/$(git rev-parse --abbrev-ref HEAD)" > nul 2>&1
                if ($?) {
                    Write-Host "Old changes branch deleted"
                } else {
                    Write-Host "Old changes branch not found"
                }
                
                if ((git diff --name-only | Where-Object { $_ -ne 'LastPack.log' }) -or (git ls-files --others --exclude-standard)) {
                    Write-Host "Changes detected"
                    git checkout -B "win-pack-changes/$(git rev-parse --abbrev-ref HEAD)"
                    
                    git add -A
                    git commit -m "win changes"
                    git push -f --set-upstream origin "$(git rev-parse --abbrev-ref HEAD)"
                } else {
                    Write-Host "No changes detected"
                }
          